name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  create-docker-img:
    runs-on: ubuntu:latest
    steps:
      - run: docker build -t sample-app-img . 
  launch-docker-cont:
    runs-on: ubuntu:latest
    steps:
     - run: docker run -d -p 8080:80 sample-app-img:latest
     - run: npm run build --if-present
